displayName: Traefik OIDC
type: middleware

import: github.com/gjirm/traefikoidc

summary: |
  Middleware adding OIDC authentication to traefik routes.

testData:
  providerURL: https://accounts.google.com
  clientID: 1234567890.apps.googleusercontent.com
  clientSecret: secret
  callbackURL: /oauth2/callback
  logoutURL: /oauth2/logout
  scopes:
    - openid
    - email
    - profile
  sessionEncryptionKey: potato-secret
  forceHTTPS: false
  logLevel: debug
  rateLimit: 100
  sessionTimeout: 86400
  cookieName: _raczylo_oidc
